"""
OpenTelemetry instrumentation for FastAPI services.
Generated by claude_harness_forge scaffold.

Provides auto-tracing, structured logging, and Prometheus-compatible metrics.

Placeholders:
    {{SERVICE_NAME}}   — Logical service name for traces/metrics
    {{OTLP_ENDPOINT}}  — OTLP collector endpoint (e.g. http://localhost:4317)
"""

from __future__ import annotations

import logging
import time
from contextvars import ContextVar
from functools import wraps
from typing import Any, Callable, TypeVar

import structlog
from fastapi import FastAPI, Request, Response
from opentelemetry import metrics, trace
from opentelemetry.context import attach, detach
from opentelemetry.exporter.otlp.proto.grpc.metric_exporter import OTLPMetricExporter
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.propagate import extract, inject
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.semconv.resource import ResourceAttributes
from opentelemetry.trace import StatusCode
from starlette.middleware.base import BaseHTTPMiddleware

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SERVICE_NAME = "{{SERVICE_NAME}}"
OTLP_ENDPOINT = "{{OTLP_ENDPOINT}}"

F = TypeVar("F", bound=Callable[..., Any])

# ---------------------------------------------------------------------------
# Resource definition
# ---------------------------------------------------------------------------

_resource = Resource.create(
    {
        ResourceAttributes.SERVICE_NAME: SERVICE_NAME,
        ResourceAttributes.SERVICE_VERSION: "0.1.0",
    }
)

# ---------------------------------------------------------------------------
# Tracer setup
# ---------------------------------------------------------------------------

_tracer_provider = TracerProvider(resource=_resource)
_tracer_provider.add_span_processor(
    BatchSpanProcessor(
        OTLPSpanExporter(endpoint=OTLP_ENDPOINT, insecure=True),
        max_queue_size=2048,
        max_export_batch_size=512,
        schedule_delay_millis=5000,
    )
)
trace.set_tracer_provider(_tracer_provider)

tracer = trace.get_tracer(SERVICE_NAME)

# ---------------------------------------------------------------------------
# Meter setup
# ---------------------------------------------------------------------------

_metric_reader = PeriodicExportingMetricReader(
    OTLPMetricExporter(endpoint=OTLP_ENDPOINT, insecure=True),
    export_interval_millis=15000,
)
_meter_provider = MeterProvider(resource=_resource, metric_readers=[_metric_reader])
metrics.set_meter_provider(_meter_provider)

meter = metrics.get_meter(SERVICE_NAME)

# Counters and histograms
request_counter = meter.create_counter(
    name="http_requests_total",
    description="Total HTTP requests",
    unit="1",
)

error_counter = meter.create_counter(
    name="http_errors_total",
    description="Total HTTP error responses (4xx, 5xx)",
    unit="1",
)

request_latency = meter.create_histogram(
    name="http_request_duration_seconds",
    description="HTTP request latency in seconds",
    unit="s",
)

# ---------------------------------------------------------------------------
# Structured logging
# ---------------------------------------------------------------------------

_current_trace_ctx: ContextVar[dict[str, str]] = ContextVar(
    "current_trace_ctx", default={}
)


def _add_trace_context(
    _logger: Any, _method: str, event_dict: dict[str, Any]
) -> dict[str, Any]:
    """Structlog processor that injects trace/span IDs into every log line."""
    span = trace.get_current_span()
    ctx = span.get_span_context()
    if ctx and ctx.trace_id:
        event_dict["trace_id"] = f"{ctx.trace_id:032x}"
        event_dict["span_id"] = f"{ctx.span_id:016x}"
    return event_dict


structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt="iso"),
        _add_trace_context,
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer(),
    ],
    wrapper_class=structlog.stdlib.BoundLogger,
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

logger = structlog.get_logger(SERVICE_NAME)

# ---------------------------------------------------------------------------
# FastAPI middleware
# ---------------------------------------------------------------------------


class OTelMiddleware(BaseHTTPMiddleware):
    """Captures per-request metrics and ensures trace context propagation."""

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        # Propagate incoming trace context (e.g. from an upstream gateway)
        ctx = extract(carrier=dict(request.headers))
        token = attach(ctx)

        method = request.method
        path = request.url.path
        start = time.perf_counter()

        try:
            response = await call_next(request)
        except Exception:
            error_counter.add(1, {"method": method, "path": path, "status": "500"})
            raise
        finally:
            elapsed = time.perf_counter() - start
            status = str(getattr(response, "status_code", 500))

            request_counter.add(1, {"method": method, "path": path, "status": status})
            request_latency.record(elapsed, {"method": method, "path": path})

            if int(status) >= 400:
                error_counter.add(
                    1, {"method": method, "path": path, "status": status}
                )

            detach(token)

        return response


# ---------------------------------------------------------------------------
# Span decorator for service functions
# ---------------------------------------------------------------------------


def traced(
    name: str | None = None,
    *,
    record_exception: bool = True,
    attributes: dict[str, str] | None = None,
) -> Callable[[F], F]:
    """Decorator that wraps a sync or async function in an OTel span.

    Usage::

        @traced("compute_embeddings")
        async def compute_embeddings(texts: list[str]) -> list[list[float]]:
            ...
    """

    def decorator(fn: F) -> F:
        span_name = name or fn.__qualname__

        if _is_coroutine_function(fn):

            @wraps(fn)
            async def _async_wrapper(*args: Any, **kwargs: Any) -> Any:
                with tracer.start_as_current_span(
                    span_name, attributes=attributes or {}
                ) as span:
                    try:
                        result = await fn(*args, **kwargs)
                    except Exception as exc:
                        span.set_status(StatusCode.ERROR, str(exc))
                        if record_exception:
                            span.record_exception(exc)
                        raise
                    return result

            return _async_wrapper  # type: ignore[return-value]

        @wraps(fn)
        def _sync_wrapper(*args: Any, **kwargs: Any) -> Any:
            with tracer.start_as_current_span(
                span_name, attributes=attributes or {}
            ) as span:
                try:
                    result = fn(*args, **kwargs)
                except Exception as exc:
                    span.set_status(StatusCode.ERROR, str(exc))
                    if record_exception:
                        span.record_exception(exc)
                    raise
                return result

        return _sync_wrapper  # type: ignore[return-value]

    return decorator


def _is_coroutine_function(fn: Callable) -> bool:
    import asyncio
    import inspect

    return asyncio.iscoroutinefunction(fn) or inspect.iscoroutinefunction(fn)


# ---------------------------------------------------------------------------
# Instrument a FastAPI app
# ---------------------------------------------------------------------------


def instrument_app(app: FastAPI) -> FastAPI:
    """Call once at app startup to wire OTel into the FastAPI instance.

    Example::

        app = FastAPI(title="{{SERVICE_NAME}}")
        instrument_app(app)
    """
    # Auto-instrument routes (creates spans per endpoint)
    FastAPIInstrumentor.instrument_app(app)

    # Add metric-collection middleware
    app.add_middleware(OTelMiddleware)

    logger.info("otel_initialized", service=SERVICE_NAME, endpoint=OTLP_ENDPOINT)
    return app


# ---------------------------------------------------------------------------
# Shutdown hook
# ---------------------------------------------------------------------------


def shutdown() -> None:
    """Flush pending spans and metrics. Call during app shutdown."""
    _tracer_provider.shutdown()
    _meter_provider.shutdown()
    logger.info("otel_shutdown", service=SERVICE_NAME)
