/**
 * OpenTelemetry instrumentation for Express / Node.js services.
 * Generated by claude_harness_forge scaffold.
 *
 * Provides auto-tracing, structured JSON logging, and Prometheus-compatible metrics.
 *
 * Placeholders:
 *   {{SERVICE_NAME}}   — Logical service name for traces/metrics
 *   {{OTLP_ENDPOINT}}  — OTLP collector endpoint (e.g. http://localhost:4317)
 *
 * IMPORTANT: Import this module BEFORE any other application code so the SDK
 * can monkey-patch HTTP/Express before they are loaded.
 *
 *   import { instrumentApp, shutdown } from "./otel-setup";
 */

import { OTLPMetricExporter } from "@opentelemetry/exporter-metrics-otlp-grpc";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-grpc";
import { ExpressInstrumentation } from "@opentelemetry/instrumentation-express";
import { HttpInstrumentation } from "@opentelemetry/instrumentation-http";
import { Resource } from "@opentelemetry/resources";
import {
  MeterProvider,
  PeriodicExportingMetricReader,
} from "@opentelemetry/sdk-metrics";
import {
  BatchSpanProcessor,
  NodeTracerProvider,
} from "@opentelemetry/sdk-trace-node";
import {
  ATTR_SERVICE_NAME,
  ATTR_SERVICE_VERSION,
} from "@opentelemetry/semantic-conventions";
import {
  context,
  Counter,
  Histogram,
  Meter,
  metrics,
  propagation,
  Span,
  SpanStatusCode,
  trace,
  Tracer,
} from "@opentelemetry/api";
import type { Express, NextFunction, Request, Response } from "express";
import pino from "pino";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const SERVICE_NAME = "{{SERVICE_NAME}}";
const OTLP_ENDPOINT = "{{OTLP_ENDPOINT}}";

// ---------------------------------------------------------------------------
// Resource
// ---------------------------------------------------------------------------

const resource = new Resource({
  [ATTR_SERVICE_NAME]: SERVICE_NAME,
  [ATTR_SERVICE_VERSION]: "0.1.0",
});

// ---------------------------------------------------------------------------
// Tracer provider
// ---------------------------------------------------------------------------

const traceExporter = new OTLPTraceExporter({
  url: OTLP_ENDPOINT,
});

const tracerProvider = new NodeTracerProvider({
  resource,
  spanProcessors: [
    new BatchSpanProcessor(traceExporter, {
      maxQueueSize: 2048,
      maxExportBatchSize: 512,
      scheduledDelayMillis: 5000,
    }),
  ],
});

tracerProvider.register();

export const tracer: Tracer = trace.getTracer(SERVICE_NAME);

// ---------------------------------------------------------------------------
// Meter provider
// ---------------------------------------------------------------------------

const metricExporter = new OTLPMetricExporter({
  url: OTLP_ENDPOINT,
});

const metricReader = new PeriodicExportingMetricReader({
  exporter: metricExporter,
  exportIntervalMillis: 15000,
});

const meterProvider = new MeterProvider({
  resource,
  readers: [metricReader],
});

metrics.setGlobalMeterProvider(meterProvider);

const meter: Meter = metrics.getMeter(SERVICE_NAME);

// Counters and histograms
const requestCounter: Counter = meter.createCounter("http_requests_total", {
  description: "Total HTTP requests",
  unit: "1",
});

const errorCounter: Counter = meter.createCounter("http_errors_total", {
  description: "Total HTTP error responses (4xx, 5xx)",
  unit: "1",
});

const requestLatency: Histogram = meter.createHistogram(
  "http_request_duration_seconds",
  {
    description: "HTTP request latency in seconds",
    unit: "s",
  },
);

// ---------------------------------------------------------------------------
// Structured logging (pino, JSON format, with trace context)
// ---------------------------------------------------------------------------

export const logger = pino({
  name: SERVICE_NAME,
  level: process.env.LOG_LEVEL ?? "info",
  formatters: {
    log(obj: Record<string, unknown>) {
      const span = trace.getActiveSpan();
      if (span) {
        const ctx = span.spanContext();
        obj.trace_id = ctx.traceId;
        obj.span_id = ctx.spanId;
      }
      return obj;
    },
  },
  timestamp: pino.stdTimeFunctions.isoTime,
});

// ---------------------------------------------------------------------------
// Express middleware
// ---------------------------------------------------------------------------

/**
 * Express middleware that records per-request metrics and propagates
 * incoming trace context from upstream callers.
 */
function otelMiddleware(req: Request, res: Response, next: NextFunction): void {
  const parentCtx = propagation.extract(context.active(), req.headers);

  context.with(parentCtx, () => {
    const method = req.method;
    const path = req.route?.path ?? req.path;
    const start = process.hrtime.bigint();

    res.on("finish", () => {
      const elapsed =
        Number(process.hrtime.bigint() - start) / 1_000_000_000;
      const status = String(res.statusCode);

      requestCounter.add(1, { method, path, status });
      requestLatency.record(elapsed, { method, path });

      if (res.statusCode >= 400) {
        errorCounter.add(1, { method, path, status });
      }
    });

    next();
  });
}

// ---------------------------------------------------------------------------
// Span decorator for service functions
// ---------------------------------------------------------------------------

/**
 * Wraps an async function in an OpenTelemetry span.
 *
 * @example
 * const computeEmbeddings = traced("compute_embeddings", async (texts: string[]) => {
 *   // ...
 * });
 */
export function traced<TArgs extends unknown[], TReturn>(
  spanName: string,
  fn: (...args: TArgs) => Promise<TReturn>,
  attributes?: Record<string, string>,
): (...args: TArgs) => Promise<TReturn> {
  return async (...args: TArgs): Promise<TReturn> => {
    return tracer.startActiveSpan(
      spanName,
      { attributes: attributes ?? {} },
      async (span: Span) => {
        try {
          const result = await fn(...args);
          return result;
        } catch (err) {
          span.setStatus({
            code: SpanStatusCode.ERROR,
            message: err instanceof Error ? err.message : String(err),
          });
          span.recordException(
            err instanceof Error ? err : new Error(String(err)),
          );
          throw err;
        } finally {
          span.end();
        }
      },
    );
  };
}

// ---------------------------------------------------------------------------
// Instrument an Express app
// ---------------------------------------------------------------------------

/**
 * Call once at app startup to wire OTel into the Express instance.
 *
 * @example
 * const app = express();
 * instrumentApp(app);
 */
export function instrumentApp(app: Express): Express {
  // Auto-instrument HTTP and Express (creates spans per route)
  new HttpInstrumentation().enable();
  new ExpressInstrumentation().enable();

  // Add metric-collection middleware (must be early in the stack)
  app.use(otelMiddleware);

  logger.info({ service: SERVICE_NAME, endpoint: OTLP_ENDPOINT }, "otel_initialized");
  return app;
}

// ---------------------------------------------------------------------------
// Shutdown hook
// ---------------------------------------------------------------------------

/**
 * Flush pending spans and metrics. Call during graceful shutdown.
 *
 * @example
 * process.on("SIGTERM", async () => {
 *   await shutdown();
 *   process.exit(0);
 * });
 */
export async function shutdown(): Promise<void> {
  await tracerProvider.shutdown();
  await meterProvider.shutdown();
  logger.info({ service: SERVICE_NAME }, "otel_shutdown");
}
