"""
RAG (Retrieval-Augmented Generation) pipeline.
Generated by claude_harness_forge scaffold.

End-to-end pipeline: document loading, chunking, embedding, vector storage,
hybrid retrieval, optional reranking, and LLM generation with evaluation helpers.

Placeholders:
    {{EMBEDDING_MODEL}}  — Embedding model name (e.g. text-embedding-3-small, all-MiniLM-L6-v2)
    {{VECTOR_DB}}        — Vector store backend: "pgvector" | "chromadb"
    {{CHUNK_SIZE}}       — Target chunk size in characters (e.g. 1000)
    {{CHUNK_OVERLAP}}    — Overlap between chunks in characters (e.g. 200)
    {{LLM_MODEL}}        — LLM model for generation (e.g. gpt-4o, claude-sonnet-4-20250514)
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, Protocol, Sequence

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

EMBEDDING_MODEL: str = "{{EMBEDDING_MODEL}}"
VECTOR_DB: Literal["pgvector", "chromadb"] = "{{VECTOR_DB}}"  # type: ignore[assignment]
CHUNK_SIZE: int = int("{{CHUNK_SIZE}}" if "{{CHUNK_SIZE}}".isdigit() else "1000")
CHUNK_OVERLAP: int = int("{{CHUNK_OVERLAP}}" if "{{CHUNK_OVERLAP}}".isdigit() else "200")
LLM_MODEL: str = "{{LLM_MODEL}}"


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class Document:
    """A loaded document with metadata."""

    content: str
    metadata: dict[str, Any] = field(default_factory=dict)
    doc_id: str = ""

    def __post_init__(self) -> None:
        if not self.doc_id:
            self.doc_id = hashlib.sha256(self.content.encode()).hexdigest()[:16]


@dataclass
class Chunk:
    """A text chunk derived from a document."""

    text: str
    doc_id: str
    chunk_index: int
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def chunk_id(self) -> str:
        return f"{self.doc_id}:{self.chunk_index}"


@dataclass
class RetrievalResult:
    """A single retrieval hit."""

    chunk: Chunk
    score: float
    source: Literal["vector", "keyword", "hybrid"] = "vector"


@dataclass
class GenerationResult:
    """LLM generation output with provenance."""

    answer: str
    source_chunks: list[Chunk]
    model: str
    usage: dict[str, int] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Document loader
# ---------------------------------------------------------------------------


class DocumentLoader:
    """Load documents from PDF, Markdown, and plain text files."""

    _SUPPORTED_EXTENSIONS = {".pdf", ".md", ".txt", ".text", ".markdown"}

    def load(self, path: str | Path) -> list[Document]:
        path = Path(path)
        if path.is_dir():
            return self._load_directory(path)
        return [self._load_file(path)]

    def _load_directory(self, directory: Path) -> list[Document]:
        docs: list[Document] = []
        for p in sorted(directory.rglob("*")):
            if p.suffix.lower() in self._SUPPORTED_EXTENSIONS:
                try:
                    docs.append(self._load_file(p))
                except Exception:
                    logger.warning("Failed to load %s", p, exc_info=True)
        return docs

    def _load_file(self, path: Path) -> Document:
        ext = path.suffix.lower()
        metadata = {"source": str(path), "filename": path.name}

        if ext == ".pdf":
            content = self._load_pdf(path)
        else:
            content = path.read_text(encoding="utf-8")

        return Document(content=content, metadata=metadata)

    @staticmethod
    def _load_pdf(path: Path) -> str:
        try:
            import pymupdf  # PyMuPDF

            doc = pymupdf.open(str(path))
            pages = [page.get_text() for page in doc]
            doc.close()
            return "\n\n".join(pages)
        except ImportError:
            raise ImportError(
                "PyMuPDF is required for PDF loading. Install with: pip install pymupdf"
            )


# ---------------------------------------------------------------------------
# Chunking service
# ---------------------------------------------------------------------------


class ChunkingStrategy(ABC):
    """Base class for chunking strategies."""

    @abstractmethod
    def chunk(self, document: Document) -> list[Chunk]:
        ...


class FixedSizeChunker(ChunkingStrategy):
    """Split text into fixed-size chunks with overlap."""

    def __init__(
        self,
        chunk_size: int = CHUNK_SIZE,
        chunk_overlap: int = CHUNK_OVERLAP,
    ) -> None:
        if chunk_overlap >= chunk_size:
            raise ValueError("chunk_overlap must be less than chunk_size")
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

    def chunk(self, document: Document) -> list[Chunk]:
        text = document.content
        chunks: list[Chunk] = []
        start = 0
        index = 0

        while start < len(text):
            end = start + self.chunk_size

            # Try to break at a sentence or paragraph boundary
            if end < len(text):
                boundary = self._find_boundary(text, start, end)
                if boundary > start:
                    end = boundary

            chunk_text = text[start:end].strip()
            if chunk_text:
                chunks.append(
                    Chunk(
                        text=chunk_text,
                        doc_id=document.doc_id,
                        chunk_index=index,
                        metadata={**document.metadata, "char_start": start, "char_end": end},
                    )
                )
                index += 1

            start = end - self.chunk_overlap
            if start <= (end - self.chunk_size):
                # Prevent infinite loop on degenerate input
                start = end

        return chunks

    @staticmethod
    def _find_boundary(text: str, start: int, end: int) -> int:
        """Walk backwards from end to find a paragraph or sentence break."""
        search_region = text[max(start, end - 200) : end]
        # Prefer paragraph break
        para = search_region.rfind("\n\n")
        if para != -1:
            return max(start, end - 200) + para + 2
        # Fall back to sentence break
        sentence = max(search_region.rfind(". "), search_region.rfind(".\n"))
        if sentence != -1:
            return max(start, end - 200) + sentence + 2
        return end


class SemanticChunker(ChunkingStrategy):
    """Split text at semantic boundaries (headings, paragraph breaks).

    Falls back to fixed-size splitting for blocks that exceed max_chunk_size.
    """

    def __init__(self, max_chunk_size: int = CHUNK_SIZE) -> None:
        self.max_chunk_size = max_chunk_size
        self._fallback = FixedSizeChunker(chunk_size=max_chunk_size, chunk_overlap=CHUNK_OVERLAP)

    def chunk(self, document: Document) -> list[Chunk]:
        # Split on markdown headings and double newlines
        sections = re.split(r"(?=^#{1,3}\s)|\n{2,}", document.content, flags=re.MULTILINE)
        chunks: list[Chunk] = []
        index = 0

        for section in sections:
            section = section.strip()
            if not section:
                continue

            if len(section) <= self.max_chunk_size:
                chunks.append(
                    Chunk(
                        text=section,
                        doc_id=document.doc_id,
                        chunk_index=index,
                        metadata=document.metadata,
                    )
                )
                index += 1
            else:
                # Oversized section: use fixed-size chunker
                temp_doc = Document(content=section, metadata=document.metadata, doc_id=document.doc_id)
                for sub in self._fallback.chunk(temp_doc):
                    sub.chunk_index = index
                    chunks.append(sub)
                    index += 1

        return chunks


class ChunkingService:
    """Facade for chunking with configurable strategy."""

    def __init__(self, strategy: Literal["fixed", "semantic"] = "fixed") -> None:
        self.strategy: ChunkingStrategy
        if strategy == "semantic":
            self.strategy = SemanticChunker()
        else:
            self.strategy = FixedSizeChunker()

    def chunk_documents(self, documents: list[Document]) -> list[Chunk]:
        all_chunks: list[Chunk] = []
        for doc in documents:
            all_chunks.extend(self.strategy.chunk(doc))
        logger.info("Chunked %d documents into %d chunks", len(documents), len(all_chunks))
        return all_chunks


# ---------------------------------------------------------------------------
# Embedding service
# ---------------------------------------------------------------------------


class EmbeddingProvider(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]:
        ...


class OpenAIEmbeddings:
    """Embedding via OpenAI API (text-embedding-3-small, ada-002, etc.)."""

    def __init__(self, model: str = EMBEDDING_MODEL) -> None:
        try:
            from openai import OpenAI
        except ImportError:
            raise ImportError("Install openai: pip install openai")
        self.client = OpenAI()
        self.model = model

    def embed(self, texts: list[str]) -> list[list[float]]:
        response = self.client.embeddings.create(input=texts, model=self.model)
        return [item.embedding for item in response.data]


class SentenceTransformerEmbeddings:
    """Local embedding via sentence-transformers."""

    def __init__(self, model: str = EMBEDDING_MODEL) -> None:
        try:
            from sentence_transformers import SentenceTransformer
        except ImportError:
            raise ImportError("Install sentence-transformers: pip install sentence-transformers")
        self.model = SentenceTransformer(model)

    def embed(self, texts: list[str]) -> list[list[float]]:
        embeddings = self.model.encode(texts, show_progress_bar=False)
        return embeddings.tolist()


class EmbeddingService:
    """Facade for embedding with configurable provider."""

    def __init__(self, provider: Literal["openai", "local"] = "openai") -> None:
        self.provider: EmbeddingProvider
        if provider == "local":
            self.provider = SentenceTransformerEmbeddings()
        else:
            self.provider = OpenAIEmbeddings()

    def embed_texts(self, texts: list[str], batch_size: int = 64) -> list[list[float]]:
        all_embeddings: list[list[float]] = []
        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            all_embeddings.extend(self.provider.embed(batch))
        return all_embeddings

    def embed_chunks(self, chunks: list[Chunk], batch_size: int = 64) -> list[list[float]]:
        return self.embed_texts([c.text for c in chunks], batch_size=batch_size)


# ---------------------------------------------------------------------------
# Vector store client
# ---------------------------------------------------------------------------


class VectorStoreClient(ABC):
    """Abstract vector store interface."""

    @abstractmethod
    def upsert(self, ids: list[str], embeddings: list[list[float]], metadatas: list[dict[str, Any]], texts: list[str]) -> None:
        ...

    @abstractmethod
    def query(self, embedding: list[float], top_k: int = 10) -> list[RetrievalResult]:
        ...

    @abstractmethod
    def delete(self, ids: list[str]) -> None:
        ...


class PgVectorClient(VectorStoreClient):
    """pgvector-backed vector store using psycopg."""

    def __init__(self, connection_string: str | None = None, table: str = "embeddings") -> None:
        try:
            import psycopg
            from pgvector.psycopg import register_vector
        except ImportError:
            raise ImportError("Install pgvector and psycopg: pip install pgvector psycopg[binary]")

        self.conn_str = connection_string or os.environ.get(
            "DATABASE_URL", "postgresql://localhost:5432/rag"
        )
        self.table = table
        self._conn = psycopg.connect(self.conn_str)
        register_vector(self._conn)
        self._ensure_table()

    def _ensure_table(self) -> None:
        with self._conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {self.table} (
                    id TEXT PRIMARY KEY,
                    embedding vector,
                    metadata JSONB,
                    content TEXT
                )
                """
            )
            cur.execute(
                f"""
                CREATE INDEX IF NOT EXISTS {self.table}_embedding_idx
                ON {self.table} USING ivfflat (embedding vector_cosine_ops)
                WITH (lists = 100)
                """
            )
        self._conn.commit()

    def upsert(self, ids: list[str], embeddings: list[list[float]], metadatas: list[dict[str, Any]], texts: list[str]) -> None:
        with self._conn.cursor() as cur:
            for id_, emb, meta, text in zip(ids, embeddings, metadatas, texts):
                cur.execute(
                    f"""
                    INSERT INTO {self.table} (id, embedding, metadata, content)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (id) DO UPDATE SET embedding = EXCLUDED.embedding,
                        metadata = EXCLUDED.metadata, content = EXCLUDED.content
                    """,
                    (id_, emb, json.dumps(meta), text),
                )
        self._conn.commit()

    def query(self, embedding: list[float], top_k: int = 10) -> list[RetrievalResult]:
        with self._conn.cursor() as cur:
            cur.execute(
                f"""
                SELECT id, content, metadata, 1 - (embedding <=> %s::vector) AS score
                FROM {self.table}
                ORDER BY embedding <=> %s::vector
                LIMIT %s
                """,
                (embedding, embedding, top_k),
            )
            results = []
            for row in cur.fetchall():
                chunk = Chunk(
                    text=row[1],
                    doc_id=json.loads(row[2]).get("doc_id", ""),
                    chunk_index=0,
                    metadata=json.loads(row[2]),
                )
                results.append(RetrievalResult(chunk=chunk, score=row[3], source="vector"))
            return results

    def delete(self, ids: list[str]) -> None:
        with self._conn.cursor() as cur:
            cur.execute(f"DELETE FROM {self.table} WHERE id = ANY(%s)", (ids,))
        self._conn.commit()


class ChromaDBClient(VectorStoreClient):
    """ChromaDB-backed vector store."""

    def __init__(self, collection_name: str = "rag_collection", persist_dir: str = "./chroma_data") -> None:
        try:
            import chromadb
        except ImportError:
            raise ImportError("Install chromadb: pip install chromadb")

        self.client = chromadb.PersistentClient(path=persist_dir)
        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            metadata={"hnsw:space": "cosine"},
        )

    def upsert(self, ids: list[str], embeddings: list[list[float]], metadatas: list[dict[str, Any]], texts: list[str]) -> None:
        self.collection.upsert(ids=ids, embeddings=embeddings, metadatas=metadatas, documents=texts)

    def query(self, embedding: list[float], top_k: int = 10) -> list[RetrievalResult]:
        results = self.collection.query(query_embeddings=[embedding], n_results=top_k, include=["documents", "metadatas", "distances"])
        hits: list[RetrievalResult] = []
        for i in range(len(results["ids"][0])):
            chunk = Chunk(
                text=results["documents"][0][i],
                doc_id=results["metadatas"][0][i].get("doc_id", ""),
                chunk_index=0,
                metadata=results["metadatas"][0][i],
            )
            # ChromaDB returns distances; convert to similarity for cosine
            score = 1.0 - results["distances"][0][i]
            hits.append(RetrievalResult(chunk=chunk, score=score, source="vector"))
        return hits

    def delete(self, ids: list[str]) -> None:
        self.collection.delete(ids=ids)


def create_vector_store(backend: str = VECTOR_DB, **kwargs: Any) -> VectorStoreClient:
    """Factory for vector store clients."""
    if backend == "pgvector":
        return PgVectorClient(**kwargs)
    elif backend == "chromadb":
        return ChromaDBClient(**kwargs)
    else:
        raise ValueError(f"Unsupported vector store backend: {backend}")


# ---------------------------------------------------------------------------
# Retrieval service (hybrid search)
# ---------------------------------------------------------------------------


class RetrievalService:
    """Hybrid search combining vector similarity with keyword matching."""

    def __init__(
        self,
        vector_store: VectorStoreClient,
        embedding_service: EmbeddingService,
        keyword_weight: float = 0.3,
        vector_weight: float = 0.7,
    ) -> None:
        self.vector_store = vector_store
        self.embedding_service = embedding_service
        self.keyword_weight = keyword_weight
        self.vector_weight = vector_weight

    def search(self, query: str, top_k: int = 10) -> list[RetrievalResult]:
        """Perform hybrid search: vector similarity + BM25-style keyword scoring."""
        # Vector search
        query_embedding = self.embedding_service.embed_texts([query])[0]
        vector_results = self.vector_store.query(query_embedding, top_k=top_k * 2)

        # Keyword scoring on vector results (lightweight BM25 approximation)
        query_terms = set(query.lower().split())
        scored: list[RetrievalResult] = []

        for result in vector_results:
            chunk_terms = set(result.chunk.text.lower().split())
            overlap = len(query_terms & chunk_terms)
            keyword_score = overlap / max(len(query_terms), 1)

            combined_score = (
                self.vector_weight * result.score + self.keyword_weight * keyword_score
            )
            scored.append(
                RetrievalResult(
                    chunk=result.chunk, score=combined_score, source="hybrid"
                )
            )

        scored.sort(key=lambda r: r.score, reverse=True)
        return scored[:top_k]


# ---------------------------------------------------------------------------
# Reranking service
# ---------------------------------------------------------------------------


class RerankingService:
    """Optional reranker using a cross-encoder or API-based reranking."""

    def __init__(self, method: Literal["cross-encoder", "cohere", "none"] = "none", model: str | None = None) -> None:
        self.method = method
        self.model = model
        self._ranker: Any = None

        if method == "cross-encoder":
            try:
                from sentence_transformers import CrossEncoder
            except ImportError:
                raise ImportError("Install sentence-transformers: pip install sentence-transformers")
            self._ranker = CrossEncoder(model or "cross-encoder/ms-marco-MiniLM-L-6-v2")
        elif method == "cohere":
            try:
                import cohere
            except ImportError:
                raise ImportError("Install cohere: pip install cohere")
            self._ranker = cohere.Client(os.environ.get("COHERE_API_KEY", ""))

    def rerank(self, query: str, results: list[RetrievalResult], top_k: int = 5) -> list[RetrievalResult]:
        if self.method == "none" or not results:
            return results[:top_k]

        if self.method == "cross-encoder":
            pairs = [(query, r.chunk.text) for r in results]
            scores = self._ranker.predict(pairs)
            for result, score in zip(results, scores):
                result.score = float(score)
            results.sort(key=lambda r: r.score, reverse=True)
            return results[:top_k]

        if self.method == "cohere":
            response = self._ranker.rerank(
                query=query,
                documents=[r.chunk.text for r in results],
                top_n=top_k,
                model=self.model or "rerank-english-v3.0",
            )
            reranked = []
            for hit in response.results:
                result = results[hit.index]
                result.score = hit.relevance_score
                reranked.append(result)
            return reranked

        return results[:top_k]


# ---------------------------------------------------------------------------
# Generation service
# ---------------------------------------------------------------------------


class GenerationService:
    """Generate answers using an LLM with retrieved context."""

    SYSTEM_PROMPT = (
        "You are a helpful assistant. Answer the user's question based on the "
        "provided context. If the context does not contain enough information, "
        "say so. Cite the relevant source documents when possible."
    )

    def __init__(self, model: str = LLM_MODEL) -> None:
        self.model = model

    def generate(self, query: str, context_chunks: list[Chunk]) -> GenerationResult:
        context_text = "\n\n---\n\n".join(
            f"[Source: {c.metadata.get('source', 'unknown')}]\n{c.text}"
            for c in context_chunks
        )

        messages = [
            {"role": "system", "content": self.SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"Context:\n{context_text}\n\nQuestion: {query}",
            },
        ]

        # Supports OpenAI-compatible APIs (OpenAI, Azure, local vLLM, etc.)
        try:
            from openai import OpenAI
        except ImportError:
            raise ImportError("Install openai: pip install openai")

        client = OpenAI()
        response = client.chat.completions.create(
            model=self.model,
            messages=messages,
            temperature=0.1,
            max_tokens=2048,
        )

        usage = {}
        if response.usage:
            usage = {
                "prompt_tokens": response.usage.prompt_tokens,
                "completion_tokens": response.usage.completion_tokens,
                "total_tokens": response.usage.total_tokens,
            }

        return GenerationResult(
            answer=response.choices[0].message.content or "",
            source_chunks=context_chunks,
            model=self.model,
            usage=usage,
        )


# ---------------------------------------------------------------------------
# Evaluation helpers
# ---------------------------------------------------------------------------


class EvaluationMetrics:
    """Lightweight helpers for RAG evaluation."""

    @staticmethod
    def retrieval_precision(retrieved: list[Chunk], relevant_ids: set[str]) -> float:
        """Fraction of retrieved chunks that are relevant."""
        if not retrieved:
            return 0.0
        hits = sum(1 for c in retrieved if c.chunk_id in relevant_ids)
        return hits / len(retrieved)

    @staticmethod
    def retrieval_recall(retrieved: list[Chunk], relevant_ids: set[str]) -> float:
        """Fraction of relevant chunks that were retrieved."""
        if not relevant_ids:
            return 0.0
        hits = sum(1 for c in retrieved if c.chunk_id in relevant_ids)
        return hits / len(relevant_ids)

    @staticmethod
    def answer_faithfulness(answer: str, context_chunks: list[Chunk]) -> dict[str, Any]:
        """Basic faithfulness check: how many sentences in the answer can be
        attributed to the provided context. Returns a dict with score and details.

        For production use, replace with a model-graded evaluation (e.g. RAGAS).
        """
        context_text = " ".join(c.text.lower() for c in context_chunks)
        sentences = [s.strip() for s in re.split(r"[.!?]+", answer) if s.strip()]

        if not sentences:
            return {"score": 1.0, "total_sentences": 0, "grounded_sentences": 0}

        grounded = 0
        for sentence in sentences:
            words = sentence.lower().split()
            if len(words) < 3:
                grounded += 1
                continue
            # Check if a meaningful fraction of words appear in context
            overlap = sum(1 for w in words if w in context_text)
            if overlap / len(words) >= 0.5:
                grounded += 1

        return {
            "score": grounded / len(sentences),
            "total_sentences": len(sentences),
            "grounded_sentences": grounded,
        }

    @staticmethod
    def mean_reciprocal_rank(retrieved: list[Chunk], relevant_ids: set[str]) -> float:
        """Mean Reciprocal Rank of the first relevant result."""
        for i, chunk in enumerate(retrieved, start=1):
            if chunk.chunk_id in relevant_ids:
                return 1.0 / i
        return 0.0


# ---------------------------------------------------------------------------
# Pipeline orchestrator
# ---------------------------------------------------------------------------


class RAGPipeline:
    """End-to-end RAG pipeline wiring all services together."""

    def __init__(
        self,
        loader: DocumentLoader | None = None,
        chunker: ChunkingService | None = None,
        embedder: EmbeddingService | None = None,
        vector_store: VectorStoreClient | None = None,
        retriever: RetrievalService | None = None,
        reranker: RerankingService | None = None,
        generator: GenerationService | None = None,
    ) -> None:
        self.loader = loader or DocumentLoader()
        self.chunker = chunker or ChunkingService(strategy="fixed")
        self.embedder = embedder or EmbeddingService(provider="openai")
        self.vector_store = vector_store or create_vector_store()
        self.retriever = retriever or RetrievalService(self.vector_store, self.embedder)
        self.reranker = reranker or RerankingService(method="none")
        self.generator = generator or GenerationService()

    def ingest(self, source: str | Path) -> int:
        """Load, chunk, embed, and store documents from a file or directory.

        Returns the number of chunks stored.
        """
        documents = self.loader.load(source)
        chunks = self.chunker.chunk_documents(documents)
        embeddings = self.embedder.embed_chunks(chunks)

        ids = [c.chunk_id for c in chunks]
        metadatas = [c.metadata for c in chunks]
        texts = [c.text for c in chunks]

        self.vector_store.upsert(ids, embeddings, metadatas, texts)
        logger.info("Ingested %d chunks from %s", len(chunks), source)
        return len(chunks)

    def query(self, question: str, top_k: int = 5) -> GenerationResult:
        """Retrieve relevant context and generate an answer."""
        results = self.retriever.search(question, top_k=top_k * 2)
        reranked = self.reranker.rerank(question, results, top_k=top_k)
        context_chunks = [r.chunk for r in reranked]

        return self.generator.generate(question, context_chunks)
