"""
Temporal workflow boilerplate with saga pattern and human-in-the-loop approval.
Generated by claude_harness_forge scaffold.

Provides a typed workflow definition, activity stubs with retry policies,
compensating actions (saga), signal-based human approval, and worker setup.

Placeholders:
    {{WORKFLOW_NAME}}  — PascalCase workflow name (e.g. OrderProcessing)
    {{TASK_QUEUE}}     — Temporal task queue name (e.g. order-processing-queue)
    {{NAMESPACE}}      — Temporal namespace (e.g. default, production)
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import timedelta
from enum import Enum
from typing import Any, Sequence

from temporalio import activity, workflow
from temporalio.client import Client
from temporalio.common import RetryPolicy
from temporalio.worker import Worker

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

WORKFLOW_NAME = "{{WORKFLOW_NAME}}"
TASK_QUEUE = "{{TASK_QUEUE}}"
NAMESPACE = "{{NAMESPACE}}"

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class WorkflowInput:
    """Typed input for the workflow. Extend with domain-specific fields."""

    request_id: str
    payload: dict[str, Any] = field(default_factory=dict)


@dataclass
class WorkflowOutput:
    """Typed output for the workflow."""

    request_id: str
    status: str = "completed"
    results: dict[str, Any] = field(default_factory=dict)
    compensated: bool = False


class ApprovalDecision(str, Enum):
    APPROVED = "approved"
    REJECTED = "rejected"


@dataclass
class CompensationRecord:
    """Tracks an activity that succeeded and may need rollback."""

    activity_name: str
    compensation_name: str
    input_data: dict[str, Any]


# ---------------------------------------------------------------------------
# Activity definitions
# ---------------------------------------------------------------------------


@activity.defn(name="validate_input")
async def validate_input(input_data: dict[str, Any]) -> dict[str, Any]:
    """Validate the workflow input. Raises on invalid data."""
    activity.logger.info("Validating input for request %s", input_data.get("request_id"))

    # Domain-specific validation goes here
    if not input_data.get("request_id"):
        raise ValueError("request_id is required")

    return {"validated": True, "request_id": input_data["request_id"]}


@activity.defn(name="process_step_one")
async def process_step_one(input_data: dict[str, Any]) -> dict[str, Any]:
    """First processing step. Replace with domain logic."""
    activity.logger.info("Processing step one for %s", input_data.get("request_id"))

    # Simulate work — replace with actual business logic
    result = {
        "request_id": input_data["request_id"],
        "step": "one",
        "output": "step_one_result",
    }
    return result


@activity.defn(name="compensate_step_one")
async def compensate_step_one(input_data: dict[str, Any]) -> dict[str, Any]:
    """Compensating action for step one (saga rollback)."""
    activity.logger.info("Compensating step one for %s", input_data.get("request_id"))

    # Undo whatever process_step_one did
    return {"compensated": True, "step": "one", "request_id": input_data.get("request_id")}


@activity.defn(name="process_step_two")
async def process_step_two(input_data: dict[str, Any]) -> dict[str, Any]:
    """Second processing step. Replace with domain logic."""
    activity.logger.info("Processing step two for %s", input_data.get("request_id"))

    result = {
        "request_id": input_data["request_id"],
        "step": "two",
        "output": "step_two_result",
    }
    return result


@activity.defn(name="compensate_step_two")
async def compensate_step_two(input_data: dict[str, Any]) -> dict[str, Any]:
    """Compensating action for step two (saga rollback)."""
    activity.logger.info("Compensating step two for %s", input_data.get("request_id"))

    return {"compensated": True, "step": "two", "request_id": input_data.get("request_id")}


@activity.defn(name="finalize")
async def finalize(input_data: dict[str, Any]) -> dict[str, Any]:
    """Final step: commit results, send notifications, etc."""
    activity.logger.info("Finalizing workflow for %s", input_data.get("request_id"))

    return {
        "request_id": input_data["request_id"],
        "finalized": True,
    }


@activity.defn(name="send_notification")
async def send_notification(input_data: dict[str, Any]) -> dict[str, Any]:
    """Send a notification (email, Slack, webhook, etc.)."""
    activity.logger.info(
        "Sending notification: %s for %s",
        input_data.get("type", "info"),
        input_data.get("request_id"),
    )

    # Replace with actual notification logic
    return {"notified": True}


# ---------------------------------------------------------------------------
# Workflow definition
# ---------------------------------------------------------------------------

# Shared retry policy for activities
_default_retry = RetryPolicy(
    initial_interval=timedelta(seconds=1),
    backoff_coefficient=2.0,
    maximum_interval=timedelta(minutes=5),
    maximum_attempts=5,
    non_retryable_error_types=["ValueError"],
)


@workflow.defn(name=WORKFLOW_NAME)
class ProcessingWorkflow:
    """Main workflow with saga compensation and human-in-the-loop approval.

    Flow:
        1. validate_input
        2. process_step_one
        3. Wait for human approval (signal)
        4. process_step_two
        5. finalize

    On failure at any step, previously completed activities are compensated
    in reverse order (saga pattern).
    """

    def __init__(self) -> None:
        self._approval_decision: ApprovalDecision | None = None
        self._compensation_stack: list[CompensationRecord] = []

    # --- Signals --------------------------------------------------------

    @workflow.signal(name="approval_decision")
    async def handle_approval(self, decision: str) -> None:
        """Signal handler for human-in-the-loop approval.

        Send this signal from an external system (UI, Slack bot, CLI) to
        unblock the workflow.
        """
        workflow.logger.info("Received approval decision: %s", decision)
        self._approval_decision = ApprovalDecision(decision)

    # --- Queries --------------------------------------------------------

    @workflow.query(name="get_status")
    def get_status(self) -> dict[str, Any]:
        """Query the current workflow state."""
        return {
            "approval_decision": self._approval_decision.value if self._approval_decision else "pending",
            "compensation_stack_depth": len(self._compensation_stack),
        }

    # --- Main workflow logic -------------------------------------------

    @workflow.run
    async def run(self, input: WorkflowInput) -> WorkflowOutput:
        """Execute the workflow with saga compensation."""
        request_id = input.request_id
        workflow.logger.info("Starting %s for request %s", WORKFLOW_NAME, request_id)

        base_data = {"request_id": request_id, **input.payload}

        try:
            # Step 1: Validate
            await workflow.execute_activity(
                validate_input,
                base_data,
                start_to_close_timeout=timedelta(seconds=30),
                retry_policy=_default_retry,
            )

            # Step 2: Process step one
            step_one_result = await workflow.execute_activity(
                process_step_one,
                base_data,
                start_to_close_timeout=timedelta(minutes=5),
                retry_policy=_default_retry,
            )
            self._compensation_stack.append(
                CompensationRecord(
                    activity_name="process_step_one",
                    compensation_name="compensate_step_one",
                    input_data=base_data,
                )
            )

            # Step 3: Human-in-the-loop — wait for approval signal
            await self._wait_for_approval(request_id)

            if self._approval_decision == ApprovalDecision.REJECTED:
                workflow.logger.info("Workflow rejected by approver, compensating")
                await self._compensate()
                return WorkflowOutput(
                    request_id=request_id,
                    status="rejected",
                    compensated=True,
                )

            # Step 4: Process step two
            step_two_result = await workflow.execute_activity(
                process_step_two,
                {**base_data, "step_one": step_one_result},
                start_to_close_timeout=timedelta(minutes=5),
                retry_policy=_default_retry,
            )
            self._compensation_stack.append(
                CompensationRecord(
                    activity_name="process_step_two",
                    compensation_name="compensate_step_two",
                    input_data=base_data,
                )
            )

            # Step 5: Finalize
            final_result = await workflow.execute_activity(
                finalize,
                {**base_data, "step_one": step_one_result, "step_two": step_two_result},
                start_to_close_timeout=timedelta(minutes=2),
                retry_policy=_default_retry,
            )

            # Success notification
            await workflow.execute_activity(
                send_notification,
                {"request_id": request_id, "type": "success", "details": final_result},
                start_to_close_timeout=timedelta(seconds=30),
                retry_policy=_default_retry,
            )

            return WorkflowOutput(
                request_id=request_id,
                status="completed",
                results=final_result,
            )

        except Exception as exc:
            workflow.logger.error("Workflow failed: %s — running compensation", exc)

            # Notify about failure
            await workflow.execute_activity(
                send_notification,
                {"request_id": request_id, "type": "failure", "error": str(exc)},
                start_to_close_timeout=timedelta(seconds=30),
                retry_policy=_default_retry,
            )

            # Saga: compensate in reverse order
            await self._compensate()

            return WorkflowOutput(
                request_id=request_id,
                status="failed",
                results={"error": str(exc)},
                compensated=True,
            )

    async def _wait_for_approval(self, request_id: str) -> None:
        """Block until an approval signal arrives or timeout is reached."""
        # Notify that approval is needed
        await workflow.execute_activity(
            send_notification,
            {"request_id": request_id, "type": "approval_required"},
            start_to_close_timeout=timedelta(seconds=30),
            retry_policy=_default_retry,
        )

        # Wait with a timeout — adjust for your SLA
        approval_timeout = timedelta(hours=24)
        try:
            await workflow.wait_condition(
                lambda: self._approval_decision is not None,
                timeout=approval_timeout,
            )
        except asyncio.TimeoutError:
            workflow.logger.warning("Approval timed out after %s", approval_timeout)
            raise TimeoutError(
                f"Human approval not received within {approval_timeout} for {request_id}"
            )

    async def _compensate(self) -> None:
        """Run compensation activities in reverse order (saga pattern)."""
        while self._compensation_stack:
            record = self._compensation_stack.pop()
            workflow.logger.info("Compensating: %s", record.compensation_name)
            try:
                compensation_fn = _COMPENSATION_REGISTRY[record.compensation_name]
                await workflow.execute_activity(
                    compensation_fn,
                    record.input_data,
                    start_to_close_timeout=timedelta(minutes=5),
                    retry_policy=RetryPolicy(
                        initial_interval=timedelta(seconds=2),
                        backoff_coefficient=2.0,
                        maximum_interval=timedelta(minutes=10),
                        maximum_attempts=10,
                    ),
                )
            except Exception:
                workflow.logger.error(
                    "Compensation failed for %s — manual intervention required",
                    record.compensation_name,
                    exc_info=True,
                )


# Registry mapping compensation names to activity functions
_COMPENSATION_REGISTRY = {
    "compensate_step_one": compensate_step_one,
    "compensate_step_two": compensate_step_two,
}

# All activities that the worker needs to register
ALL_ACTIVITIES = [
    validate_input,
    process_step_one,
    compensate_step_one,
    process_step_two,
    compensate_step_two,
    finalize,
    send_notification,
]


# ---------------------------------------------------------------------------
# Worker setup
# ---------------------------------------------------------------------------


async def run_worker(
    temporal_address: str = "localhost:7233",
    namespace: str = NAMESPACE,
) -> None:
    """Start a Temporal worker that executes the workflow and activities."""
    client = await Client.connect(temporal_address, namespace=namespace)

    worker = Worker(
        client,
        task_queue=TASK_QUEUE,
        workflows=[ProcessingWorkflow],
        activities=ALL_ACTIVITIES,
    )

    logger.info(
        "Starting worker — queue=%s namespace=%s", TASK_QUEUE, namespace
    )
    await worker.run()


# ---------------------------------------------------------------------------
# Client helpers
# ---------------------------------------------------------------------------


async def start_workflow(
    input: WorkflowInput,
    temporal_address: str = "localhost:7233",
    namespace: str = NAMESPACE,
) -> str:
    """Start a new workflow execution. Returns the workflow run ID."""
    client = await Client.connect(temporal_address, namespace=namespace)

    handle = await client.start_workflow(
        ProcessingWorkflow.run,
        input,
        id=f"{WORKFLOW_NAME}-{input.request_id}",
        task_queue=TASK_QUEUE,
    )

    logger.info("Started workflow %s (run_id=%s)", handle.id, handle.result_run_id)
    return handle.id


async def send_approval(
    workflow_id: str,
    decision: ApprovalDecision,
    temporal_address: str = "localhost:7233",
    namespace: str = NAMESPACE,
) -> None:
    """Send an approval signal to a running workflow."""
    client = await Client.connect(temporal_address, namespace=namespace)
    handle = client.get_workflow_handle(workflow_id)
    await handle.signal(ProcessingWorkflow.handle_approval, decision.value)
    logger.info("Sent %s signal to %s", decision.value, workflow_id)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(run_worker())
